#!/bin/sh

set -e

. "$SETUP_DATA_DIR/common-data"
. "$SETUP_DATA_DIR/common-functions"

# schroot 1.6 deprecates script-config.  Once we stop building
# for precise, we can drop this entire conditional block and simply
# source $SETUP_DATA_DIR/common-config
if [ -f "$SETUP_DATA_DIR/common-config" ]; then
    . "$SETUP_DATA_DIR/common-config"
elif [ -n  "$CHROOT_SCRIPT_CONFIG" ] && \
    [ -f "$CHROOT_SCRIPT_CONFIG" ]; then
    . "$CHROOT_SCRIPT_CONFIG"
elif [ "$STATUS" = "ok" ]; then
    fatal "Debathena has no idea how to deal with this schroot configuration."
fi

if [ $STAGE = "setup-start" ]; then
    info "Adding messagebus to access list for session ${SESSION_ID}"
    sed -i "/^root-users/s/$/,messagebus/" /var/lib/schroot/session/"${SESSION_ID}"
fi

if [ $STAGE = "setup-stop" ]; then
    info "Inhibiting dbus-daemon-launch-helper during chroot shutdown"
    touch /var/run/debathena-inhibit-dbus-helper
fi

